### ISSUE TITLE
Cursor misalignment in the GUI

### ISSUE THREAD

**Issue by ahelwer** [prismmodelchecker/prism#127] opened 2019-10-05 17:55 UTC
As I type in the GUI, the cursor becomes misaligned from where text is being added/deleted. This is because when I type a character, the cursor is moved forward several pixels beyond the width of the character; as more characters are typed on the line, the cursor moves further and further right of its actual position in the text. Here is a screenshot:

![image](https://user-images.githubusercontent.com/718765/66258815-82dd6400-e75e-11e9-89ad-f391b9d5878f.png)

The cursor is at the end of the red error indicator, even though it is operating at the end of the last "f".

I am using PRISM version 4.5 with Java version 13 2019-09-17, on a 4k screen.

**Comment by ahelwer** [comment] 2019-10-11 00:58
I'm running Windows. Curiously when I run Java 8 update 221 I don't experience the misaligned cursor issue, but in Java 11.0.4 and 13 I do.

**Comment by kleinj** [comment] 2019-10-23 05:23
I tried to reproduce this bug using an Amazon AWS Windows VM. Using the Remote Desktop with 4k resolution, I did not see the cursor issue. It might be that one needs a physical high DPI monitor to trigger it.

This is a really curious bug and I'd like to get to the bottom of it. @ahelwer: If I would build a small, pared down version of our editor that uses as few PRISM-related modifications as possible, would you be able/willing to give that a try? That way we could determine whether it's due to our code or a more generic Java issue.

**Comment by kleinj** [comment] 2019-10-26 12:33
So, I reviewed our code that is concerned with drawing the editor and have a theory what might go wrong. To test that, I have produced a stripped down version of our editor:

https://prismmodelchecker.org/downloads/cursor-test-jdk8.jar
https://prismmodelchecker.org/downloads/cursor-test-jdk9.jar

The two JAR files can be called via `java -jar cursor-test-jdk8.jar` and `java -jar cursor-test-jdk8.jar plain` (similarily with `...-jdk9.jar`). When started with `plain`, it will just use the default rendering kit from Java Swing, without the parameter it uses the customized one from PRISM (used for syntax highlighting).

If I'm guessing right, when used with a JDK>=9, `plain` should be fine for both JARs, while without `plain` the `...-jdk8.jar` will show the problem whereas the `...-jdk9.jar` should be fine. @ahelwer, it would be much appreciated if you could check this out.


So, what's my guess? When looking at the code, I noticed that the `drawUnselectedText`/`drawSelectedText` methods using integer coordinates where deprecated in Java 9, being replaced by ones with float coordinates. In the documentation for the int ones, there is a note regarding an assumption of 72ppi resolution. So, it might be the case that with a high DPI display there are rounding discrepancies between the text width computations used by Java for the cursor placement and the methods we use (with int-based coordinates) for drawing the text. The `...-jdk9.jar` uses the newer, float-based methods. In the Windows-VM where I tried it, there was no effect, but I was neither able to reproduce the issue before.

For sake of completeness: The code for the tests is at https://github.com/kleinj/prism/tree/issue-127-test-jdk9 and https://github.com/kleinj/prism/tree/issue-127-test.

**Comment by ahelwer** [comment] 2019-10-27 20:08
Using Java 13 on a 4k screen:

- cursor-test-jdk8.jar WITHOUT plain: YES problem
- cursor-test-jdk8.jar WITH plain: NO problem
- cursor-test-jdk9.jar WITHOUT plain: NO problem
- cursor-test-jdk9.jar WITH plain: NO problem

Well done!

**Comment by kleinj** [comment] 2019-10-27 21:40
@ahelwer: Thanks a lot for testing! The results are as expected. I think Java 8 did not have special handling for high DPI and thus is not affected. And the new, float-based methods were only introduced in Java 9, so they won't work/compile with 8.

@davexparker: This puts us in a bit of a bind. On Windows with high DPI displays, the users need to use Java>=9 to get a reasonable experience with the PRISM GUI. For these users, it makes sense to fix this issue by switching to the newer text drawing methods. However, that would mean that it would not run on Java 8 anymore, as the corresponding API is not available in that version of the JRE/JDK...

So, I see a few options:
1. Generally requite Java >=9 and just fix it.
2. Release 2 versions for Windows, one for Java 8 and one for Java 9 (including a patch that fixes this issue).
3. Find a (potentially hacky) way to dynamically switch between the int-based and float-based methods, depending on the Java version.

To see how hacky (3) would be, I'll have to look into the code a bit more and think about it.

As for (1), i think there are a few holdouts on Java 8. It might nevertheless be fine, as the installation options for JREs/JDKs>=9 that are not provided by Oracle have gotten a lot better recently.

**Comment by ahelwer** [comment] 2021-02-22 15:22
Update: I am experiencing a similar issue, although in the other direction - the cursor does not move far enough! Environment info:

- Windows 10
- PRISM 4.6
- Java OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
- 4k screen set to 2x UIscaling in Windows display settings

Here's a screenshot, the cursor's logical position is at EOL:

![image](https://user-images.githubusercontent.com/718765/108728727-d7ba7f80-74f7-11eb-90c8-c4e5449c09eb.png)

**Comment by davexparker** [comment] 2021-02-22 15:32
Thanks for the continued reports @ahelwer! Would you able to check if @kleinj's test code `cursor-test-jdk9.jar` from above eliminates the problem (with respect to `cursor-test-jdk8.jar`)? Time has moved on and I guess it is less problematic now to start requiring JDK>=9 and fix the issue this way.

**Comment by ahelwer** [comment] 2021-03-02 18:47
@davexparker unfortunately after testing I can't get the `cursor-test-jdk8.jar` to reproduce the issue. Running all jars with/without `plain` has the cursor's position in the expected position.

**Comment by davexparker** [comment] 2021-03-09 11:37
Thanks for trying @ahelwer. I've now applied the same changes to the actual PRISM editor in the latest codebase. I'm not sure if you are compiling from source on Windows, so I put a binary for it here:

https://prismmodelchecker.org/downloads/prism-4.6.dev-win64-installer.exe

If that does not show the cursor problem on the same setup for you, I think it is worth pushing the fix to the main release.

**Comment by ahelwer** [comment] 2021-03-10 18:00
I can confirm this fixes the problem! The issue actually only shows up when I increase the editor font size, which explains why I wasn't able to repro it with the jars up above (since there's no way to increase the font size in those stripped-down editors. Screenshots, with font size set to 16 and cursor set to logical end of line:

PRISM 4.6 release:

![image](https://user-images.githubusercontent.com/718765/110674895-570aad00-81a0-11eb-9135-decbe195f53d.png)

Your dev changes:

![image](https://user-images.githubusercontent.com/718765/110675046-7dc8e380-81a0-11eb-8b97-625cd7d78a45.png)

**Comment by davexparker** [comment] 2021-03-11 08:47
Excellent! Thanks for all your efforts @ahelwer. I will get fix this merged.

**Closed** 2021-03-11 19:45 UTC

**Comment by cStuartHardwick** [comment] 2022-10-14 21:53
I seem to be having the same issue, but it's not clear from the above quite how to fix it. 
I'm working on a branch of an open source app using a bespoke copy of com.lightdev.app.shtm.SHTMLEditorPane to edit rich text.
I get very similar results with the caret not lining up with the true entry point on screen.

I patched my app to work with the current (non-bespoke) version of com.lightdev.app.shtm.SHTMLEditorPane and no change, so I patched it further to work with a plain Jane JEditorPane, which is as simple as I can make it.

This did NOT solve the problem. 
If I type and numeral repeatedly, the cursor (caret) leads, drifting further and further to the right of the insertion point.
If I type and hold and alphabetic charactor, the cursor lags ever further behind (to the left).
If I type and hold tilde, equals, or dash, the caret stayes true.
The misalignment is only left-right. Each line displayed the same behavior.

I am using Java 16.
Any idea where I should look?

**Comment by davexparker** [comment] 2022-10-15 16:27
If it helps, the code fix in question is in commit 1b1e41b384581304a80ae136a6bbc29d3fb2b78f.

From memory, the key thing was to switch to newer versions of methods such as `drawUnselectedText` (inherited from `javax.swing.text.PlainView`), which took `Graphics2D` rather than `Graphics`.
